const PDFDocument = require('pdfkit');

const COMPANY_NAME = process.env.COMPANY_NAME || 'G-Tech Africa Ltd';
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
  'August', 'September', 'October', 'November', 'December'];

const fmt = (n) => Number(n || 0).toLocaleString('en-KE', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

/**
 * Renders a single payslip as a PDF and returns it as a Buffer.
 * payslip: a row from the payslips table, joined with employee fields
 * (employee_no, first_name, last_name — see payrollService.getPayrollRun).
 */
function renderPayslipPdf(payslip, { periodMonth, periodYear }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.font('Helvetica-Bold').fontSize(16).text(COMPANY_NAME);
    doc.font('Helvetica').fontSize(10).fillColor('#555').text('Payslip');
    doc.moveDown(1.2);

    doc.fillColor('#000').fontSize(11);
    doc.text(`Employee: ${payslip.first_name} ${payslip.last_name}`);
    doc.text(`Employee No.: ${payslip.employee_no}`);
    doc.text(`Pay period: ${MONTHS[periodMonth - 1]} ${periodYear}`);
    doc.moveDown(1);

    const col1 = 50, col2 = 400;
    const row = (label, value, opts = {}) => {
      doc.font(opts.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(10.5);
      doc.text(label, col1, doc.y);
      doc.text(`KES ${fmt(value)}`, col2, doc.y - doc.currentLineHeight(), { width: 145, align: 'right' });
      doc.moveDown(0.5);
    };
    const divider = () => {
      doc.moveTo(col1, doc.y).lineTo(545, doc.y).strokeColor('#ccc').stroke();
      doc.moveDown(0.5);
    };

    doc.font('Helvetica-Bold').fontSize(12).text('Earnings');
    doc.moveDown(0.3);
    row('Basic salary', payslip.basic_salary);
    row('Taxable allowances', payslip.taxable_allowances);
    row('Non-taxable allowances', payslip.non_taxable_allowances);
    divider();
    row('Gross pay', payslip.gross_pay, { bold: true });
    doc.moveDown(0.8);

    doc.font('Helvetica-Bold').fontSize(12).text('Statutory deductions');
    doc.moveDown(0.3);
    row('NSSF Tier I', payslip.nssf_tier1);
    row('NSSF Tier II', payslip.nssf_tier2);
    row('SHA (SHIF)', payslip.sha_contribution);
    row('Housing Levy', payslip.housing_levy);
    row('Taxable income', payslip.taxable_income);
    row('PAYE (before relief)', payslip.paye_before_relief);
    row('Personal relief', -payslip.personal_relief);
    row('PAYE payable', payslip.paye, { bold: true });
    if (Number(payslip.other_deductions_total) > 0) {
      row('Other deductions', payslip.other_deductions_total);
    }
    divider();
    row('Total deductions', payslip.total_deductions, { bold: true });
    doc.moveDown(0.8);

    doc.font('Helvetica-Bold').fontSize(13).fillColor('#2C5C4A');
    doc.text('Net pay', col1, doc.y);
    doc.text(`KES ${fmt(payslip.net_pay)}`, col2, doc.y - doc.currentLineHeight(), { width: 145, align: 'right' });

    doc.fillColor('#888').fontSize(8).text(
      'Generated by Ledger Payroll. This is a system-generated document.',
      50, 780, { width: 495, align: 'center' }
    );

    doc.end();
  });
}

/**
 * Renders a KRA-style P9 (Tax Deduction Card) for one employee covering one
 * calendar year, aggregated from that employee's payslips for every payroll
 * run in that year. Mirrors the columns on KRA's official P9A template:
 * https://www.kra.go.ke/images/publications/P9-FORM-Template-2025.pdf
 *
 * This is a computed summary for the employer/employee's own records, not
 * an official KRA-issued document — always reconcile against PAYE returns
 * actually filed on iTax before distributing.
 */
function renderP9Pdf(employee, monthlyPayslips, year) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40, layout: 'landscape' });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.font('Helvetica-Bold').fontSize(15).text(`${COMPANY_NAME}`);
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#555').text('TAX DEDUCTION CARD (P9) — YEAR ' + year);
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(10).fillColor('#000');
    doc.text(`Employee: ${employee.first_name} ${employee.last_name}    Employee No.: ${employee.employee_no}    KRA PIN: ${employee.kra_pin || 'N/A'}`);
    doc.moveDown(0.8);

    const headers = ['Month', 'Basic Salary', 'Allowances', 'Gross Pay', 'NSSF', 'Taxable Pay', 'Tax Charged', 'Relief', 'PAYE Tax'];
    const colWidths = [70, 85, 85, 85, 70, 85, 85, 70, 85];
    const startX = 40;
    let y = doc.y;

    const drawRow = (cells, opts = {}) => {
      let x = startX;
      doc.font(opts.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9);
      cells.forEach((cell, i) => {
        doc.text(String(cell), x, y, { width: colWidths[i], align: i === 0 ? 'left' : 'right' });
        x += colWidths[i];
      });
      y += 18;
    };

    drawRow(headers, { bold: true });
    doc.moveTo(startX, y - 4).lineTo(startX + colWidths.reduce((a, b) => a + b, 0), y - 4).strokeColor('#999').stroke();

    const totals = { basic: 0, allowances: 0, gross: 0, nssf: 0, taxable: 0, tax: 0, relief: 0, paye: 0 };
    for (let m = 1; m <= 12; m++) {
      const p = monthlyPayslips.find((row) => row.period_month === m);
      if (p) {
        const allowances = Number(p.taxable_allowances) + Number(p.non_taxable_allowances);
        totals.basic += Number(p.basic_salary);
        totals.allowances += allowances;
        totals.gross += Number(p.gross_pay);
        totals.nssf += Number(p.nssf_total);
        totals.taxable += Number(p.taxable_income);
        totals.tax += Number(p.paye_before_relief);
        totals.relief += Number(p.personal_relief);
        totals.paye += Number(p.paye);
        drawRow([
          MONTHS[m - 1], fmt(p.basic_salary), fmt(allowances), fmt(p.gross_pay),
          fmt(p.nssf_total), fmt(p.taxable_income), fmt(p.paye_before_relief),
          fmt(p.personal_relief), fmt(p.paye),
        ]);
      } else {
        drawRow([MONTHS[m - 1], '—', '—', '—', '—', '—', '—', '—', '—']);
      }
    }

    doc.moveTo(startX, y - 2).lineTo(startX + colWidths.reduce((a, b) => a + b, 0), y - 2).strokeColor('#333').stroke();
    y += 4;
    drawRow([
      'TOTAL', fmt(totals.basic), fmt(totals.allowances), fmt(totals.gross),
      fmt(totals.nssf), fmt(totals.taxable), fmt(totals.tax), fmt(totals.relief), fmt(totals.paye),
    ], { bold: true });

    doc.font('Helvetica').fontSize(8).fillColor('#888').text(
      'This is a computed summary generated from payroll records, not an official KRA-issued document. ' +
      'Reconcile against PAYE returns filed on iTax before distributing to the employee.',
      40, 540, { width: 760 }
    );

    doc.end();
  });
}

module.exports = { renderPayslipPdf, renderP9Pdf };
