const PDFDocument = require('pdfkit');

const COMPANY_NAME = process.env.COMPANY_NAME || 'G-Tech Africa Ltd';
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
  'August', 'September', 'October', 'November', 'December'];

const fmt = (n) => Number(n || 0).toLocaleString('en-KE', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const round2 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;

/**
 * Renders a single payslip as a PDF and returns it as a Buffer.
 * payslip: a row from the payslips table, joined with employee fields
 * (employee_no, first_name, last_name — see payrollService.getPayrollRun).
 */
function renderPayslipPdf(payslip, { periodMonth, periodYear }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.font('Helvetica-Bold').fontSize(16).text(COMPANY_NAME);
    doc.font('Helvetica').fontSize(10).fillColor('#555').text('Payslip');
    doc.moveDown(1.2);

    doc.fillColor('#000').fontSize(11);
    doc.text(`Employee: ${payslip.first_name} ${payslip.last_name}`);
    doc.text(`Employee No.: ${payslip.employee_no}`);
    doc.text(`Pay period: ${MONTHS[periodMonth - 1]} ${periodYear}`);
    doc.moveDown(1);

    const col1 = 50, col2 = 400;
    const row = (label, value, opts = {}) => {
      doc.font(opts.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(10.5);
      doc.text(label, col1, doc.y);
      doc.text(`KES ${fmt(value)}`, col2, doc.y - doc.currentLineHeight(), { width: 145, align: 'right' });
      doc.moveDown(0.5);
    };
    const divider = () => {
      doc.moveTo(col1, doc.y).lineTo(545, doc.y).strokeColor('#ccc').stroke();
      doc.moveDown(0.5);
    };

    doc.font('Helvetica-Bold').fontSize(12).text('Earnings');
    doc.moveDown(0.3);
    row('Basic salary', payslip.basic_salary);
    row('Taxable allowances', payslip.taxable_allowances);
    row('Non-taxable allowances', payslip.non_taxable_allowances);
    divider();
    row('Gross pay', payslip.gross_pay, { bold: true });
    doc.moveDown(0.8);

    doc.font('Helvetica-Bold').fontSize(12).text('Statutory deductions');
    doc.moveDown(0.3);
    row('NSSF Tier I', payslip.nssf_tier1);
    row('NSSF Tier II', payslip.nssf_tier2);
    row('SHA (SHIF)', payslip.sha_contribution);
    row('Housing Levy', payslip.housing_levy);
    row('Taxable income', payslip.taxable_income);
    row('PAYE (before relief)', payslip.paye_before_relief);
    row('Personal relief', -payslip.personal_relief);
    row('PAYE payable', payslip.paye, { bold: true });
    if (Number(payslip.other_deductions_total) > 0) {
      row('Other deductions', payslip.other_deductions_total);
    }
    divider();
    row('Total deductions', payslip.total_deductions, { bold: true });
    doc.moveDown(0.8);

    doc.font('Helvetica-Bold').fontSize(13).fillColor('#2C5C4A');
    doc.text('Net pay', col1, doc.y);
    doc.text(`KES ${fmt(payslip.net_pay)}`, col2, doc.y - doc.currentLineHeight(), { width: 145, align: 'right' });

    doc.fillColor('#888').fontSize(8).text(
      'Generated by Ledger Payroll. This is a system-generated document.',
      50, 780, { width: 495, align: 'center' }
    );

    doc.end();
  });
}

/**
 * Renders a KRA-style P9 (Tax Deduction Card) for one employee covering one
 * calendar year, aggregated from that employee's payslips for every payroll
 * run in that year. Mirrors the columns on KRA's official P9A template:
 * https://www.kra.go.ke/images/publications/P9-FORM-Template-2025.pdf
 *
 * This is a computed summary for the employer/employee's own records, not
 * an official KRA-issued document — always reconcile against PAYE returns
 * actually filed on iTax before distributing.
 */
function renderP9Pdf(employee, monthlyPayslips, year) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 30, layout: 'landscape' });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = doc.page.width;

    drawShieldLogo(doc, 30, 24, 34);
    doc.font('Times-Bold').fontSize(14).fillColor(BRAND_COLORS.ink).text(COMPANY_NAME, 74, 26);
    doc.font('Times-Roman').fontSize(9).fillColor(BRAND_COLORS.inkSoft)
      .text('Tax Deduction Card — P9A format — Year ' + year, 74, 44);
    doc.font('Helvetica').fontSize(7.5).fillColor('#999')
      .text('Company-generated, following the KRA P9A layout — not an official KRA document.', pageWidth - 260, 26, { width: 230, align: 'right' });

    doc.moveTo(30, 66).lineTo(pageWidth - 30, 66).lineWidth(1).strokeColor(BRAND_COLORS.brass).stroke();
    doc.font('Helvetica').fontSize(9).fillColor('#000');
    doc.text(`Employee: ${employee.first_name} ${employee.last_name}    Employee No.: ${employee.employee_no}    KRA PIN: ${employee.kra_pin || 'N/A'}`, 30, 74);

    const headers = ['Month', 'A\nGross\nSalary', 'B\nBenefits\nNon-Cash', 'C\nValue of\nQuarters', 'D\nTotal Gross\nPay (A+B+C)', 'E1\nNSSF', 'E2\nPension', 'E3\nSHA', 'E4\nHousing\nLevy', 'G\nTotal\nDeductions', 'H\nChargeable\nPay (D-G)', 'Tax\nCharged', 'Personal\nRelief', 'PAYE\nTax'];
    const colWidths = [52, 56, 52, 52, 62, 48, 48, 48, 52, 56, 62, 56, 52, 56];
    const startX = 30;
    let y = 96;

    const drawRow = (cells, opts = {}) => {
      let x = startX;
      doc.font(opts.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(opts.bold ? 7.5 : 7);
      cells.forEach((cell, i) => {
        doc.text(String(cell), x + 2, y, { width: colWidths[i] - 4, align: i === 0 ? 'left' : 'right' });
        x += colWidths[i];
      });
      y += opts.headerRow ? 34 : 14;
    };

    drawRow(headers, { bold: true, headerRow: true });
    doc.moveTo(startX, y - 10).lineTo(startX + colWidths.reduce((a, b) => a + b, 0), y - 10).strokeColor('#999').stroke();

    const totals = { gross: 0, totalGross: 0, nssf: 0, pension: 0, sha: 0, housing: 0, deductions: 0, chargeable: 0, tax: 0, relief: 0, paye: 0 };
    for (let m = 1; m <= 12; m++) {
      const p = monthlyPayslips.find((row) => row.period_month === m);
      if (p) {
        const grossSalary = Number(p.basic_salary) + Number(p.taxable_allowances) + Number(p.overtime_pay || 0);
        const totalGross = Number(p.gross_pay);
        const nssf = Number(p.nssf_total);
        const pension = Number(p.pension_contribution || 0);
        const sha = Number(p.sha_contribution);
        const housing = Number(p.housing_levy);
        const totalDeductions = round2(nssf + pension + sha + housing);
        const chargeable = Number(p.taxable_income);

        totals.gross += grossSalary; totals.totalGross += totalGross; totals.nssf += nssf;
        totals.pension += pension; totals.sha += sha; totals.housing += housing;
        totals.deductions += totalDeductions; totals.chargeable += chargeable;
        totals.tax += Number(p.paye_before_relief); totals.relief += Number(p.personal_relief); totals.paye += Number(p.paye);

        drawRow([
          MONTHS[m - 1], fmt(grossSalary), '0.00', '0.00', fmt(totalGross),
          fmt(nssf), fmt(pension), fmt(sha), fmt(housing), fmt(totalDeductions),
          fmt(chargeable), fmt(p.paye_before_relief), fmt(p.personal_relief), fmt(p.paye),
        ]);
      } else {
        drawRow([MONTHS[m - 1], '—', '—', '—', '—', '—', '—', '—', '—', '—', '—', '—', '—', '—']);
      }
    }

    doc.moveTo(startX, y - 2).lineTo(startX + colWidths.reduce((a, b) => a + b, 0), y - 2).strokeColor('#333').stroke();
    y += 4;
    drawRow([
      'TOTAL', fmt(totals.gross), '0.00', '0.00', fmt(totals.totalGross),
      fmt(totals.nssf), fmt(totals.pension), fmt(totals.sha), fmt(totals.housing), fmt(totals.deductions),
      fmt(totals.chargeable), fmt(totals.tax), fmt(totals.relief), fmt(totals.paye),
    ], { bold: true });

    y += 14;
    doc.font('Helvetica').fontSize(7).fillColor('#555').text(
      'B (Benefits Non-Cash) and C (Value of Quarters) are not currently tracked by this system and show as 0.00 — add manually if applicable to this employee. ' +
      'G (Total Deductions) = NSSF + Pension + SHA + Housing Levy. H (Chargeable Pay) is what PAYE is actually calculated on.',
      startX, y, { width: pageWidth - startX * 2 }
    );

    doc.font('Helvetica').fontSize(7.5).fillColor('#888').text(
      'This is a computed summary generated from payroll records, following the P9A format — not an official KRA-issued document. ' +
      'Reconcile against PAYE returns filed on iTax before distributing to the employee.',
      startX, doc.page.height - 40, { width: pageWidth - startX * 2 }
    );

    doc.end();
  });
}

/**
 * Renders KRA's monthly PAYE return (P10) for one payroll run — every
 * active employee's PAYE for that single month, as opposed to the P9's
 * one-employee-across-a-year view. This is what's actually filed on iTax
 * each month; the P9 is only produced annually.
 *
 * This is a computed summary for your own records, not an official
 * KRA-issued document — reconcile against what's actually filed on iTax.
 */
function renderP10Pdf(payrollRun, payslips, employerPin) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40, layout: 'landscape' });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.font('Helvetica-Bold').fontSize(15).text(COMPANY_NAME);
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#555').text('MONTHLY PAYE RETURN (P10)');
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor('#000');
    doc.text(`Employer PIN: ${employerPin || 'N/A'}    Period: ${MONTHS[payrollRun.period_month - 1]} ${payrollRun.period_year}`);
    doc.moveDown(0.8);

    const headers = ['Employee', 'KRA PIN', 'Basic Salary', 'Allowances', 'Gross Pay', 'NSSF', 'Taxable Pay', 'Tax Charged', 'Relief', 'PAYE Tax'];
    const colWidths = [95, 75, 75, 70, 75, 65, 75, 75, 60, 75];
    const startX = 40;
    let y = doc.y;

    const drawRow = (cells, opts = {}) => {
      let x = startX;
      doc.font(opts.bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(8.5);
      cells.forEach((cell, i) => {
        doc.text(String(cell), x, y, { width: colWidths[i], align: i < 2 ? 'left' : 'right' });
        x += colWidths[i];
      });
      y += 17;
    };

    drawRow(headers, { bold: true });
    doc.moveTo(startX, y - 3).lineTo(startX + colWidths.reduce((a, b) => a + b, 0), y - 3).strokeColor('#999').stroke();

    const totals = { basic: 0, allowances: 0, gross: 0, nssf: 0, taxable: 0, tax: 0, relief: 0, paye: 0 };
    payslips.forEach((p) => {
      const allowances = Number(p.taxable_allowances) + Number(p.non_taxable_allowances) + Number(p.overtime_pay || 0);
      totals.basic += Number(p.basic_salary);
      totals.allowances += allowances;
      totals.gross += Number(p.gross_pay);
      totals.nssf += Number(p.nssf_total);
      totals.taxable += Number(p.taxable_income);
      totals.tax += Number(p.paye_before_relief);
      totals.relief += Number(p.personal_relief);
      totals.paye += Number(p.paye);
      drawRow([
        `${p.first_name} ${p.last_name}`, p.kra_pin || 'N/A', fmt(p.basic_salary), fmt(allowances),
        fmt(p.gross_pay), fmt(p.nssf_total), fmt(p.taxable_income), fmt(p.paye_before_relief),
        fmt(p.personal_relief), fmt(p.paye),
      ]);
    });

    doc.moveTo(startX, y - 2).lineTo(startX + colWidths.reduce((a, b) => a + b, 0), y - 2).strokeColor('#333').stroke();
    y += 4;
    drawRow([
      'TOTAL', '', fmt(totals.basic), fmt(totals.allowances), fmt(totals.gross),
      fmt(totals.nssf), fmt(totals.taxable), fmt(totals.tax), fmt(totals.relief), fmt(totals.paye),
    ], { bold: true });

    doc.font('Helvetica').fontSize(8).fillColor('#888').text(
      'This is a computed summary generated from payroll records, not an official KRA-issued document. ' +
      'Reconcile against the actual PAYE return filed on iTax before relying on it.',
      40, 540, { width: 760 }
    );

    doc.end();
  });
}

/**
 * Renders a Certificate of Service — required under the Employment Act
 * when an employee's service ends. States who they were, what they did,
 * and the dates they were employed; deliberately does not include salary
 * or any compensation figures.
 */
// Shield path — same shape used for the GT logo mark in the web app
// (see index.html's <symbol id="gt-shield-logo">), reused here via
// pdfkit's SVG path support so the printed certificate carries the same
// mark instead of looking like a generic unbranded document.
const SHIELD_PATH = 'M50,4 L91,17 L91,56 Q91,87 64,105 Q57,110 50,114 Q43,110 36,105 Q9,87 9,56 L9,17 Z';
const BRAND_COLORS = { black: '#14120F', red: '#BB0000', green: '#006600', brass: '#9C6B2E', brassDark: '#7A5322', ink: '#1B231F', inkSoft: '#5B6560' };

/** Draws the flag-banded, brass-bordered shield mark at (x, y) with the given size (in points). */
function drawShieldLogo(doc, x, y, size) {
  const scale = size / 118; // path's native viewBox is 100 wide x 118 tall
  doc.save();
  doc.translate(x, y).scale(scale);

  doc.save();
  doc.path(SHIELD_PATH).clip();
  doc.rect(0, 0, 100, 33).fill(BRAND_COLORS.black);
  doc.rect(0, 33, 100, 8).fill('#ffffff');
  doc.rect(0, 41, 100, 36).fill(BRAND_COLORS.red);
  doc.rect(0, 77, 100, 8).fill('#ffffff');
  doc.rect(0, 85, 100, 33).fill(BRAND_COLORS.green);
  doc.restore();

  doc.path(SHIELD_PATH).lineWidth(3).stroke(BRAND_COLORS.brass);
  doc.font('Times-Bold').fontSize(30).fillColor('#E9C98F').text('GT', 0, 48, { width: 100, align: 'center' });
  doc.restore();
}

/** Thin flag-banded ribbon spanning the given width — the same accent used across the web app. */
function drawRibbon(doc, x, y, width, height) {
  const black = width * 0.20, white1 = width * 0.04, red = width * 0.24, white2 = width * 0.04, green = width * 0.24;
  let cx = x;
  const segs = [[black, BRAND_COLORS.black], [white1, '#ffffff'], [red, BRAND_COLORS.red], [white2, '#ffffff'], [green, BRAND_COLORS.green], [black, BRAND_COLORS.black]];
  segs.forEach(([w, color]) => { doc.rect(cx, y, w, height).fill(color); cx += w; });
}

function renderCertificateOfServicePdf(employee, { issueDate } = {}) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 0 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const margin = 55;

    // Decorative frame + top ribbon — this is a certificate, so it should look like one.
    drawRibbon(doc, 0, 0, pageWidth, 8);
    doc.rect(margin, margin, pageWidth - margin * 2, pageHeight - margin * 2)
      .lineWidth(1.5).stroke(BRAND_COLORS.brass);

    drawShieldLogo(doc, pageWidth / 2 - 26, margin + 28, 52);

    doc.font('Times-Bold').fontSize(18).fillColor(BRAND_COLORS.ink)
      .text(COMPANY_NAME, margin, margin + 96, { width: pageWidth - margin * 2, align: 'center' });
    doc.font('Times-Bold').fontSize(14).fillColor(BRAND_COLORS.brassDark)
      .text('CERTIFICATE OF SERVICE', { width: pageWidth - margin * 2, align: 'center' });

    doc.moveTo(pageWidth / 2 - 60, doc.y + 8).lineTo(pageWidth / 2 + 60, doc.y + 8)
      .lineWidth(1).stroke(BRAND_COLORS.brass);
    doc.moveDown(2.5);

    const fmtDate = (d) => new Date(d).toLocaleDateString('en-KE', { year: 'numeric', month: 'long', day: 'numeric' });
    const hireDate = employee.hire_date ? fmtDate(employee.hire_date) : null;
    const isActive = employee.status === 'active';
    const issued = fmtDate(issueDate || new Date());

    const roleClause = (employee.job_title ? ` as ${employee.job_title}` : '') + (employee.department ? ` in the ${employee.department} department` : '');
    let periodClause;
    if (!hireDate) {
      periodClause = `has been employed by ${COMPANY_NAME}${roleClause}. (Hire date not on record — verify before issuing.)`;
    } else if (isActive) {
      periodClause = `has been employed by ${COMPANY_NAME}${roleClause} since ${hireDate}, and remains an employee in good standing as of the date of this certificate.`;
    } else {
      const endDate = employee.updated_at ? fmtDate(employee.updated_at) : 'the date their employment ended';
      periodClause = `was employed by ${COMPANY_NAME}${roleClause} from ${hireDate} to ${endDate}.`;
    }

    const textX = margin + 40;
    const textWidth = pageWidth - (margin + 40) * 2;
    doc.font('Times-Roman').fontSize(12).fillColor(BRAND_COLORS.ink).lineGap(7);
    doc.text(
      `This is to certify that ${employee.first_name} ${employee.last_name}` +
      (employee.id_number ? ` (National ID No. ${employee.id_number})` : '') +
      ` ${periodClause}`,
      textX, doc.y, { width: textWidth, align: 'left' }
    );
    doc.moveDown(1);
    doc.text('During this period, their conduct and performance of duties have been satisfactory.', textX, doc.y, { width: textWidth });
    doc.moveDown(1);
    doc.text('This certificate is issued at the employee\'s request, in accordance with the Employment Act, 2007.', textX, doc.y, { width: textWidth });
    doc.moveDown(2.5);

    doc.font('Times-Roman').fontSize(11).text(`Issued on: ${issued}`, textX, doc.y);
    doc.moveDown(3.5);
    doc.moveTo(textX, doc.y).lineTo(textX + 220, doc.y).lineWidth(1).stroke(BRAND_COLORS.ink);
    doc.moveDown(0.4);
    doc.font('Times-Italic').fontSize(10.5).fillColor(BRAND_COLORS.inkSoft).text('For and on behalf of ' + COMPANY_NAME, textX, doc.y);

    doc.font('Helvetica').fontSize(8).fillColor('#999').text(
      'System-generated certificate. Verify employment dates and role details before issuing.',
      margin, pageHeight - margin - 26, { width: pageWidth - margin * 2, align: 'center' }
    );
    drawRibbon(doc, 0, pageHeight - 8, pageWidth, 8);

    doc.end();
  });
}

module.exports = { renderPayslipPdf, renderP9Pdf, renderP10Pdf, renderCertificateOfServicePdf };
